---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: plugins/git
  settings:
    tags: true

- name: release
  image: golang:1.16
  commands:
  - curl -sL https://git.io/goreleaser | bash
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag

